services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: blis
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: blis_db
    volumes:
      - ./data:/var/lib/postgresql/data
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    command: >
      sh -c "npx prisma generate &&
      npx prisma migrate deploy &&
      npm run build && npm run prod"