services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    command: >
      sh -c "npx prisma generate &&
      npx prisma migrate deploy &&
      npm run build && npm run prod"